nvme_format: fix wrong template file name
Fix wrong exmaple of control file
if the given template is used, below error occured from test
(Failed to override template arguments from control file args)

[04/01/2025 19:54:53] - FAILED - 8 - Fio start_test() - Actual: [
ToolError: [AUTOVAL TOOL ERROR] Error in starting fio job. Reason:  fio: failed parsing size=SIZE
fio: failed parsing rwmixwrite=MIXWRITE
fio: failed parsing rwmixread=MIXREAD
fio: job global dropped

Signed-off-by: Steven Seungcheol Lee <sc108.lee@samsung.com>